project:
  type: website
  output-dir: docs #puts all html files in forlder called docs 

website:
  title: "Maria Celeste Sanchez Linares"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: posts.qmd
        text: CV
    right:
      - icon: envelope
        href: "mailto:msanche2@macalester.edu"
      - text: Linked
        icon: linkedin
        href: "https://www.linkedin.com/in/maria-sanchez-linares-b6733b216"
      - text: Github
        icon: github
        href: https://github.com/yourusername
        
  page-footer:
    left: |
      &copy; Maria Sanchez Linares, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

